# Configuration des positions calibrées pour le système de tri DOFbot
# Positions extraites du code fonctionnel dofbot_tri_system.py

# Position de repos initiale (bras replié)
home_position:
  joint1: 90    # Rotation base
  joint2: 90    # Épaule
  joint3: 90    # Coude
  joint4: 90    # Poignet
  joint5: 90    # Rotation pince
  gripper: 150  # Pince ouverte

# Position d'observation (au-dessus de la zone de détection)
observation_position:
  joint1: 90
  joint2: 130
  joint3: 50
  joint4: 140
  joint5: 90
  gripper: 150  # Pince ouverte pour ne pas obstruer la vue

# Positions des 3 bacs de tri
bins:
  # Bac 1 : Déchets recyclables (papier, plastique, métal)
  recyclables:
    joint1: 45    # 45° à gauche
    joint2: 110
    joint3: 70
    joint4: 130
    joint5: 90
    description: "Bac pour déchets recyclables (papier, plastique, métal)"
  
  # Bac 2 : Déchets ménagers (organiques, non-recyclables)
  menagers:
    joint1: 90    # Centre (0° relatif)
    joint2: 110
    joint3: 70
    joint4: 130
    joint5: 90
    description: "Bac pour déchets ménagers ordinaires"
  
  # Bac 3 : Déchets dangereux (électroniques, batteries, chimiques)
  dangereux:
    joint1: 135   # 45° à droite
    joint2: 110
    joint3: 70
    joint4: 130
    joint5: 90
    description: "Bac pour déchets dangereux nécessitant traitement spécial"

# Paramètres de mouvement
movement:
  speed: 50           # Vitesse par défaut (0-100)
  acceleration: 30    # Accélération par défaut
  gripper_open: 150   # Valeur pour pince ouverte (0-255)
  gripper_close: 20   # Valeur pour pince fermée
  
  # Délais (en secondes)
  delays:
    after_move: 0.5       # Attente après un mouvement
    after_grasp: 1.0      # Attente après avoir saisi un objet
    after_release: 0.5    # Attente après avoir relâché un objet

# Limites de sécurité (degrés)
limits:
  joint1: [0, 180]    # Rotation base
  joint2: [0, 180]    # Épaule
  joint3: [0, 180]    # Coude
  joint4: [0, 180]    # Poignet
  joint5: [0, 180]    # Rotation pince
  gripper: [0, 255]   # Pince (valeur PWM)

# Mapping des classes de détection vers les bacs
class_to_bin:
  0: "dangereux"      # Classe 0 → Bac dangereux
  1: "menagers"       # Classe 1 → Bac ménagers
  2: "recyclables"    # Classe 2 → Bac recyclables
